name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Build Docker Image
        run: |
          docker build -t spring-boot-rest-api-demo:latest .